### ISSUE TITLE
transfert move in draft mode feature

### ISSUE THREAD

**Issue by rvalyi** [akretion/odoo-factoring#4]
The challenge is we need to have the cashflow accounting right in Odoo as soon we transfer an invoice and at the same time we may know the exact details of the factor conditions for each credit transfer later by checking its API (or looking on its website). API check is all the rage, but might not be possible or might be too much work to implement for factor X, se we need room for manual adjustments.
See the comment of LJ4 here: https://www.compta-online.com/affacturage-tva-t5667

**option 1: same credit transfert move, but draft instead for a later adjustment.**

in order to adjust the transfert move values using the exact factor information (or better API), we may want to leave the credit transfert move in draft for a later validation (possibly by API). The issue today is the factor transfer is is computed in _compute_factor_transfer_id which is using the full_reconcile_id. If we leave the transfer as draft, we cannot have a full_reconcile_id anymore. We can workaround this with the following patch:

```
diff --git a/account_factoring/models/account_move.py b/account_factoring/models/account_move.py
index a02f969..a47ad25 100644
--- a/account_factoring/models/account_move.py
+++ b/account_factoring/models/account_move.py
@@ -70,6 +70,20 @@ class AccountMove(models.Model):
                     lambda move: move.id not in self.ids and move.state != "cancel"
                 )
             )
+            if not factor_transfers:
+                line_with_rec_string = (
+                    inv.mapped("line_ids")
+                    .filtered(
+                        lambda line: line.credit > 0 and line.reconcile_string != False
+                    )
+                )
+                if line_with_rec_string:
+                    factor_transfers = self.env["account.move.line"].search([
+                        ('parent_state', '=', 'draft'),
+                        ('reconcile_string', '=',  line_with_rec_string.reconcile_string),
+                        ('debit', '>', 0)
+                    ]).mapped("move_id")
+
             if factor_transfers:
                 inv.factor_transfer_id = factor_transfers[0]
             else:
```

However, we are stuck anyway later because the oly reasonable way Odoo would consider the invoice as not due by the customer IS that it is reconciled with a validated move with with a DEBIT the the customer account (411 in France).

**option 2: use an interim account**

Consider this scenario today:
the following invoice:
![2021-12-28_17-59](https://user-images.githubusercontent.com/16926/147606688-a7191d8d-9216-450b-9c41-30eb6d6a02c0.png)

with the following credit transfer to the factor:
![2021-12-28_17-59_1](https://user-images.githubusercontent.com/16926/147606695-c09bcd88-32f2-4403-9f6e-1b9cca1db745.png)

Instead during the credit transfer move we would immediately reconcile the invoice with a debit on a new INTERIM FACTOR ACCOUNT. And the debit detail would be left as draft move line in a move that would be reconciled with this 1st move upon validation:

![2021-12-28_18-06](https://user-images.githubusercontent.com/16926/147607233-96887abf-4dd7-4d82-92bd-c29edabfc113.png)

The logic is a bit like with Odoo "anglo-saxon"/IFRS accounting where you post the COGS directly when validating your invoice and it will later be reconciled with the exact permanent inventory valuation move when you deliver the products.

Now the question is: what accountants think of this?

**Comment by rvalyi** [comment]
as for the move when the customer pay thge factor it isn't so much of a big deal to leave it as draft. But then we would need a way to try the same reconciliation as today when the move is validated later on.

**Comment by eepstack** [comment]
Hi @rvalyi 
I'm a French CPA currently working on this exact accounting challenge, and I wanted to share some thoughts — better late than never!
Your option 2 (interim account) is indeed the most promising approach from a French accounting standpoint, but there is a critical tax constraint that needs to be addressed.
The core tension under French law:
French tax regulations require that the customer account (411) be cleared at the moment the receivable is transferred to the factor, in order to reflect the legal transfer of ownership of the receivable. So far so good — your interim account approach handles this correctly.
However, the problem is that in Odoo, reconciling the 411 automatically triggers the CABA (cash basis VAT) entry — meaning Odoo immediately recognizes the VAT as due. But for a company using cash-basis VAT (TVA sur encaissements), the VAT on the sale is only legally due when the customer actually pays the factor, not at the moment of the receivable transfer.
So we have a direct conflict:

French accounting law → you must clear the 411 immediately upon transfer
French VAT law (cash basis) → VAT is only due upon actual payment by the customer to the factor
Odoo CABA logic → clearing the 411 = VAT becomes due immediately

What I think the correct treatment should be:
The interim factor account you propose could be the right structural answer, but the reconciliation triggering the CABA entry needs to happen not when the 411 is cleared, but when the factor confirms payment from the customer. This would require decoupling the 411 reconciliation event from the CABA trigger in Odoo — which is non-trivial given how Odoo's cash basis accounting works today.
I'm still working through the exact journal entry sequence that satisfies both constraints simultaneously. Would love to hear if others have tackled this, and whether you see a clean way to implement this decoupling in the module.
Happy to contribute further on the accounting side if useful.
